language: cpp
dist: bionic
compiler: gcc
install: pip install --user cpp-coveralls
before_script:
  - mkdir build && cd build
  - cmake ..
script: make && make test
after_success: coveralls --exclude external --exclude tests
