language: cpp
dist: bionic
compiler: gcc
branches:
  only:
    - develop
    - master
install: pip install --user cpp-coveralls
before_script:
  - mkdir build && cd build
  - cmake -DGREENBOY_COVERAGE=1 -DCMAKE_BUILD_TYPE=Debug ..
script: make && make test
after_success: coveralls --root .. --exclude build --exclude external --exclude cmake
