language: cpp
dist: bionic
sudo: required
compiler: gcc
branches:
  only:
    - develop
    - master
addons:
  apt:
    packages:
      - lcov
  pip:
    packages:
      - cpp-coveralls
install: 
  - pip install --user cpp-coveralls
before_script:
  - mkdir build && cd build
  - cmake -DGREENBOY_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug ..
script: make coverage
after_success: coveralls --root .. --exclude build --exclude external --exclude cmake
