language: cpp
dist: bionic
sudo: required
compiler: gcc
branches:
  only:
    - develop
    - master
addons:
  apt:
    packages:
      - lcov
install: 
  - pip install --user cpp-coveralls
  - gem install coveralls-lcov
before_script:
  - mkdir build && cd build
  - cmake -DGREENBOY_COVERAGE=ON -DCMAKE_BUILD_TYPE=Debug ..
script: make coverage
after_success: coveralls-lcov coverage.info
